spring:
  application:
    name: DISCOVERY-MS

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5

server:
  port: 8000